#  TUGAS 1 DATA MINING B

## CAHYA IDZNII IGAWATI (06211640000017)

## Data Integration

In [1]:
import pandas as pd
import numpy as np

In [8]:
#import data
IPM = pd.read_csv ('IPM.csv', sep=';')
Index_Kependudukan =pd.read_csv('Index_Kependudukan.csv', sep=';')

In [9]:
#mengeluarkan data IPM dan Index Kependudukan
IPM

                Provinsi  Angka Harapan Hidup  IPM 2015  IPM 2016  IPM 2017
0                   ACEH                69.52     69.45     70.00     70.60
1         SUMATERA UTARA                68.37     69.51     70.00     70.57
2         SUMATERA BARAT                68.78     69.98     70.73     71.24
3                   RIAU                70.99     70.84     71.20     71.79
4                  JAMBI                70.76     68.89     69.62     69.99
5       SUMATERA SELATAN                69.18     67.46     68.24     68.86
6               BENGKULU                68.59     68.59     69.33     69.95
7                LAMPUNG                69.95     66.95     67.65     68.25
8   KEP. BANGKA BELITUNG                69.95     69.05     69.55     69.99
9              KEP. RIAU                69.48     73.75     73.99     74.45
10           DKI JAKARTA                72.55     78.99     79.60     80.06
11            JAWA BARAT                72.47     69.50     70.05     70.69
12           JAWA TENGAH                74.08     69.49     69.98     70.52
13         DI YOGYAKARTA                74.74     77.59     78.38     78.89
14            JAWA TIMUR                70.80     68.95     69.74     70.27
15                BANTEN                69.49     70.27     70.96     71.42
16                  BALI                71.46     73.27     73.65     74.30
17   NUSA TENGGARA BARAT                65.55     65.19     65.81     66.58
18   NUSA TENGGARA TIMUR                66.07     62.67     63.13     63.73
19      KALIMANTAN BARAT                69.92     65.59     65.88     66.26
20     KALIMANTAN TENGAH                69.59     68.53     69.13     69.79
21    KALIMANTAN SELATAN                68.02     68.38     69.05     69.65
22      KALIMANTAN TIMUR                73.70     74.17     74.59     75.12
23      KALIMANTAN UTARA                72.47     68.76     69.20     69.84
24        SULAWESI UTARA                71.04     70.39     71.05     71.66
25       SULAWESI TENGAH                67.32     66.76     67.47     68.11
26      SULAWESI SELATAN                69.84     69.15     69.76     70.34
27     SULAWESI TENGGARA                70.47     68.75     69.31     69.86
28             GORONTALO                67.14     65.86     66.29     67.01
29        SULAWESI BARAT                64.34     62.96     63.60     64.30
30                MALUKU                65.40     67.05     67.60     68.19
31          MALUKU UTARA                67.54     65.91     66.63     67.20
32           PAPUA BARAT                65.32     61.73     62.21     62.99
33                 PAPUA                65.14     57.25     58.05     59.09
34                   NaN                  NaN       NaN       NaN       NaN

In [10]:
#mengeluarkan data IPM dan Index Kependudukan
Index_Kependudukan

,Provinsi,Harapan Lama Sekolah,Presentase Buta Huruf Usia >15,Presentase Buta Huruf Usia 15-44,Presentase Buta Huruf Usia >44,Rata-Rata Lama Sekolah Umur >15 Tahun
0,ACEH,14.13,2.06,0.13,6.82,9.36
1,SUMATERA UTARA,13.10,1.11,0.38,2.64,9.46
2,SUMATERA BARAT,13.94,1.15,0.19,2.87,8.97
3,RIAU,13.03,0.83,0.15,2.62,8.97
4,JAMBI,12.87,1.91,0.29,5.49,8.55
5,SUMATERA SELATAN,12.35,1.46,0.25,4.04,8.32
6,BENGKULU,13.57,2.10,0.27,6.19,8.82
7,LAMPUNG,12.46,3.11,0.16,8.81,8.10
8,KEP. BANGKA BELITUNG,11.83,2.21,0.70,5.53,8.04
9,KEP. RIAU,12.81,1.17,0.29,3.88,9.90
10,DKI JAKARTA,12.86,0.33,0.06,0.92,10.92
11,JAWA BARAT,12.42,1.77,0.26,4.71,8.41
12,JAWA TENGAH,12.57,6.61,0.36,15.38,7.70
13,DI YOGYAKARTA,15.42,5.36,0.20,12.38,9.62
14,JAWA TIMUR,13.09,8.18,1.01,18.27,7.78
15,BANTEN,12.78,2.43,0.21,7.97,8.79
16,BALI,13.21,7.10,0.40,17.58,8.84
17,NUSA TENGGARA BARAT,13.46,12.86,3.20,32.92,7.57
18,NUSA TENGGARA TIMUR,13.07,8.32,3.08,18.92,7.54
19,KALIMANTAN BARAT,12.50,7.52,1.76,20.20,7.49
20,KALIMANTAN TENGAH,12.45,0.92,0.23,2.64,8.52
21,KALIMANTAN SELATAN,12.46,1.60,0.15,4.65,8.28
22,KALIMANTAN TIMUR,13.49,1.04,0.15,3.09,9.55
23,KALIMANTAN UTARA,12.79,4.86,1.38,13.55,9.01
24,SULAWESI UTARA,12.66,0.24,0.19,0.32,9.31
25,SULAWESI TENGAH,13.04,2.31,0.84,5.39,8.56
26,SULAWESI SELATAN,13.28,8.35,2.03,20.28,8.31
27,SULAWESI TENGGARA,13.36,5.68,1.14,16.41,8.86
28,GORONTALO,13.01,1.56,0.50,3.81,7.71
29,SULAWESI BARAT,12.48,7.21,3.16,16.77,7.76
30,MALUKU,13.91,0.87,0.77,1.09,9.69
31,MALUKU UTARA,13.56,1.32,0.41,3.62,8.96
32,PAPUA BARAT,12.47,2.84,1.94,5.55,9.57
33,PAPUA,10.54,26.11,24.66,30.46,6.48
34,NaN,NaN,NaN,NaN,NaN,8.42

In [23]:
#menggabungkan dua data berdasarkan provinsi
data = pd.merge(IPM, Index_Kependudukan, on='Provinsi')
data

,Provinsi,Angka Harapan Hidup,IPM 2015,IPM 2016,IPM 2017,Harapan Lama Sekolah,Presentase Buta Huruf Usia >15,Presentase Buta Huruf Usia 15-44,Presentase Buta Huruf Usia >44,Rata-Rata Lama Sekolah Umur >15 Tahun
0,ACEH,69.52,69.45,70.00,70.60,14.13,2.06,0.13,6.82,9.36
1,SUMATERA UTARA,68.37,69.51,70.00,70.57,13.10,1.11,0.38,2.64,9.46
2,SUMATERA BARAT,68.78,69.98,70.73,71.24,13.94,1.15,0.19,2.87,8.97
3,RIAU,70.99,70.84,71.20,71.79,13.03,0.83,0.15,2.62,8.97
4,JAMBI,70.76,68.89,69.62,69.99,12.87,1.91,0.29,5.49,8.55
5,SUMATERA SELATAN,69.18,67.46,68.24,68.86,12.35,1.46,0.25,4.04,8.32
6,BENGKULU,68.59,68.59,69.33,69.95,13.57,2.10,0.27,6.19,8.82
7,LAMPUNG,69.95,66.95,67.65,68.25,12.46,3.11,0.16,8.81,8.10
8,KEP. BANGKA BELITUNG,69.95,69.05,69.55,69.99,11.83,2.21,0.70,5.53,8.04
9,KEP. RIAU,69.48,73.75,73.99,74.45,12.81,1.17,0.29,3.88,9.90
10,DKI JAKARTA,72.55,78.99,79.60,80.06,12.86,0.33,0.06,0.92,10.92
11,JAWA BARAT,72.47,69.50,70.05,70.69,12.42,1.77,0.26,4.71,8.41
12,JAWA TENGAH,74.08,69.49,69.98,70.52,12.57,6.61,0.36,15.38,7.70
13,DI YOGYAKARTA,74.74,77.59,78.38,78.89,15.42,5.36,0.20,12.38,9.62
14,JAWA TIMUR,70.80,68.95,69.74,70.27,13.09,8.18,1.01,18.27,7.78
15,BANTEN,69.49,70.27,70.96,71.42,12.78,2.43,0.21,7.97,8.79
16,BALI,71.46,73.27,73.65,74.30,13.21,7.10,0.40,17.58,8.84
17,NUSA TENGGARA BARAT,65.55,65.19,65.81,66.58,13.46,12.86,3.20,32.92,7.57
18,NUSA TENGGARA TIMUR,66.07,62.67,63.13,63.73,13.07,8.32,3.08,18.92,7.54
19,KALIMANTAN BARAT,69.92,65.59,65.88,66.26,12.50,7.52,1.76,20.20,7.49
20,KALIMANTAN TENGAH,69.59,68.53,69.13,69.79,12.45,0.92,0.23,2.64,8.52
21,KALIMANTAN SELATAN,68.02,68.38,69.05,69.65,12.46,1.60,0.15,4.65,8.28
22,KALIMANTAN TIMUR,73.70,74.17,74.59,75.12,13.49,1.04,0.15,3.09,9.55
23,KALIMANTAN UTARA,72.47,68.76,69.20,69.84,12.79,4.86,1.38,13.55,9.01
24,SULAWESI UTARA,71.04,70.39,71.05,71.66,12.66,0.24,0.19,0.32,9.31
25,SULAWESI TENGAH,67.32,66.76,67.47,68.11,13.04,2.31,0.84,5.39,8.56
26,SULAWESI SELATAN,69.84,69.15,69.76,70.34,13.28,8.35,2.03,20.28,8.31
27,SULAWESI TENGGARA,70.47,68.75,69.31,69.86,13.36,5.68,1.14,16.41,8.86
28,GORONTALO,67.14,65.86,66.29,67.01,13.01,1.56,0.50,3.81,7.71
29,SULAWESI BARAT,64.34,62.96,63.60,64.30,12.48,7.21,3.16,16.77,7.76
30,MALUKU,65.40,67.05,67.60,68.19,13.91,0.87,0.77,1.09,9.69
31,MALUKU UTARA,67.54,65.91,66.63,67.20,13.56,1.32,0.41,3.62,8.96
32,PAPUA BARAT,65.32,61.73,62.21,62.99,12.47,2.84,1.94,5.55,9.57
33,PAPUA,65.14,57.25,58.05,59.09,10.54,26.11,24.66,30.46,6.48

In [24]:
# menambah kolom baru
data['Rata-Rata IPM'] =(data['IPM 2015']+data['IPM 2016']+data['IPM 2017'])/3
data

,Provinsi,Angka Harapan Hidup,IPM 2015,IPM 2016,IPM 2017,Harapan Lama Sekolah,Presentase Buta Huruf Usia >15,Presentase Buta Huruf Usia 15-44,Presentase Buta Huruf Usia >44,Rata-Rata Lama Sekolah Umur >15 Tahun,Rata-Rata IPM
0,ACEH,69.52,69.45,70.00,70.60,14.13,2.06,0.13,6.82,9.36,70.016667
1,SUMATERA UTARA,68.37,69.51,70.00,70.57,13.10,1.11,0.38,2.64,9.46,70.026667
2,SUMATERA BARAT,68.78,69.98,70.73,71.24,13.94,1.15,0.19,2.87,8.97,70.650000
3,RIAU,70.99,70.84,71.20,71.79,13.03,0.83,0.15,2.62,8.97,71.276667
4,JAMBI,70.76,68.89,69.62,69.99,12.87,1.91,0.29,5.49,8.55,69.500000
5,SUMATERA SELATAN,69.18,67.46,68.24,68.86,12.35,1.46,0.25,4.04,8.32,68.186667
6,BENGKULU,68.59,68.59,69.33,69.95,13.57,2.10,0.27,6.19,8.82,69.290000
7,LAMPUNG,69.95,66.95,67.65,68.25,12.46,3.11,0.16,8.81,8.10,67.616667
8,KEP. BANGKA BELITUNG,69.95,69.05,69.55,69.99,11.83,2.21,0.70,5.53,8.04,69.530000
9,KEP. RIAU,69.48,73.75,73.99,74.45,12.81,1.17,0.29,3.88,9.90,74.063333
10,DKI JAKARTA,72.55,78.99,79.60,80.06,12.86,0.33,0.06,0.92,10.92,79.550000
11,JAWA BARAT,72.47,69.50,70.05,70.69,12.42,1.77,0.26,4.71,8.41,70.080000
12,JAWA TENGAH,74.08,69.49,69.98,70.52,12.57,6.61,0.36,15.38,7.70,69.996667
13,DI YOGYAKARTA,74.74,77.59,78.38,78.89,15.42,5.36,0.20,12.38,9.62,78.286667
14,JAWA TIMUR,70.80,68.95,69.74,70.27,13.09,8.18,1.01,18.27,7.78,69.653333
15,BANTEN,69.49,70.27,70.96,71.42,12.78,2.43,0.21,7.97,8.79,70.883333
16,BALI,71.46,73.27,73.65,74.30,13.21,7.10,0.40,17.58,8.84,73.740000
17,NUSA TENGGARA BARAT,65.55,65.19,65.81,66.58,13.46,12.86,3.20,32.92,7.57,65.860000
18,NUSA TENGGARA TIMUR,66.07,62.67,63.13,63.73,13.07,8.32,3.08,18.92,7.54,63.176667
19,KALIMANTAN BARAT,69.92,65.59,65.88,66.26,12.50,7.52,1.76,20.20,7.49,65.910000
20,KALIMANTAN TENGAH,69.59,68.53,69.13,69.79,12.45,0.92,0.23,2.64,8.52,69.150000
21,KALIMANTAN SELATAN,68.02,68.38,69.05,69.65,12.46,1.60,0.15,4.65,8.28,69.026667
22,KALIMANTAN TIMUR,73.70,74.17,74.59,75.12,13.49,1.04,0.15,3.09,9.55,74.626667
23,KALIMANTAN UTARA,72.47,68.76,69.20,69.84,12.79,4.86,1.38,13.55,9.01,69.266667
24,SULAWESI UTARA,71.04,70.39,71.05,71.66,12.66,0.24,0.19,0.32,9.31,71.033333
25,SULAWESI TENGAH,67.32,66.76,67.47,68.11,13.04,2.31,0.84,5.39,8.56,67.446667
26,SULAWESI SELATAN,69.84,69.15,69.76,70.34,13.28,8.35,2.03,20.28,8.31,69.750000
27,SULAWESI TENGGARA,70.47,68.75,69.31,69.86,13.36,5.68,1.14,16.41,8.86,69.306667
28,GORONTALO,67.14,65.86,66.29,67.01,13.01,1.56,0.50,3.81,7.71,66.386667
29,SULAWESI BARAT,64.34,62.96,63.60,64.30,12.48,7.21,3.16,16.77,7.76,63.620000
30,MALUKU,65.40,67.05,67.60,68.19,13.91,0.87,0.77,1.09,9.69,67.613333
31,MALUKU UTARA,67.54,65.91,66.63,67.20,13.56,1.32,0.41,3.62,8.96,66.580000
32,PAPUA BARAT,65.32,61.73,62.21,62.99,12.47,2.84,1.94,5.55,9.57,62.310000
33,PAPUA,65.14,57.25,58.05,59.09,10.54,26.11,24.66,30.46,6.48,58.130000

In [25]:
# menghapus kolom 
Data1 = data.drop(['Rata-Rata Lama Sekolah Umur >15 Tahun'], axis=1)
Data1

,Provinsi,Angka Harapan Hidup,IPM 2015,IPM 2016,IPM 2017,Harapan Lama Sekolah,Presentase Buta Huruf Usia >15,Presentase Buta Huruf Usia 15-44,Presentase Buta Huruf Usia >44,Rata-Rata IPM
0,ACEH,69.52,69.45,70.00,70.60,14.13,2.06,0.13,6.82,70.016667
1,SUMATERA UTARA,68.37,69.51,70.00,70.57,13.10,1.11,0.38,2.64,70.026667
2,SUMATERA BARAT,68.78,69.98,70.73,71.24,13.94,1.15,0.19,2.87,70.650000
3,RIAU,70.99,70.84,71.20,71.79,13.03,0.83,0.15,2.62,71.276667
4,JAMBI,70.76,68.89,69.62,69.99,12.87,1.91,0.29,5.49,69.500000
5,SUMATERA SELATAN,69.18,67.46,68.24,68.86,12.35,1.46,0.25,4.04,68.186667
6,BENGKULU,68.59,68.59,69.33,69.95,13.57,2.10,0.27,6.19,69.290000
7,LAMPUNG,69.95,66.95,67.65,68.25,12.46,3.11,0.16,8.81,67.616667
8,KEP. BANGKA BELITUNG,69.95,69.05,69.55,69.99,11.83,2.21,0.70,5.53,69.530000
9,KEP. RIAU,69.48,73.75,73.99,74.45,12.81,1.17,0.29,3.88,74.063333
10,DKI JAKARTA,72.55,78.99,79.60,80.06,12.86,0.33,0.06,0.92,79.550000
11,JAWA BARAT,72.47,69.50,70.05,70.69,12.42,1.77,0.26,4.71,70.080000
12,JAWA TENGAH,74.08,69.49,69.98,70.52,12.57,6.61,0.36,15.38,69.996667
13,DI YOGYAKARTA,74.74,77.59,78.38,78.89,15.42,5.36,0.20,12.38,78.286667
14,JAWA TIMUR,70.80,68.95,69.74,70.27,13.09,8.18,1.01,18.27,69.653333
15,BANTEN,69.49,70.27,70.96,71.42,12.78,2.43,0.21,7.97,70.883333
16,BALI,71.46,73.27,73.65,74.30,13.21,7.10,0.40,17.58,73.740000
17,NUSA TENGGARA BARAT,65.55,65.19,65.81,66.58,13.46,12.86,3.20,32.92,65.860000
18,NUSA TENGGARA TIMUR,66.07,62.67,63.13,63.73,13.07,8.32,3.08,18.92,63.176667
19,KALIMANTAN BARAT,69.92,65.59,65.88,66.26,12.50,7.52,1.76,20.20,65.910000
20,KALIMANTAN TENGAH,69.59,68.53,69.13,69.79,12.45,0.92,0.23,2.64,69.150000
21,KALIMANTAN SELATAN,68.02,68.38,69.05,69.65,12.46,1.60,0.15,4.65,69.026667
22,KALIMANTAN TIMUR,73.70,74.17,74.59,75.12,13.49,1.04,0.15,3.09,74.626667
23,KALIMANTAN UTARA,72.47,68.76,69.20,69.84,12.79,4.86,1.38,13.55,69.266667
24,SULAWESI UTARA,71.04,70.39,71.05,71.66,12.66,0.24,0.19,0.32,71.033333
25,SULAWESI TENGAH,67.32,66.76,67.47,68.11,13.04,2.31,0.84,5.39,67.446667
26,SULAWESI SELATAN,69.84,69.15,69.76,70.34,13.28,8.35,2.03,20.28,69.750000
27,SULAWESI TENGGARA,70.47,68.75,69.31,69.86,13.36,5.68,1.14,16.41,69.306667
28,GORONTALO,67.14,65.86,66.29,67.01,13.01,1.56,0.50,3.81,66.386667
29,SULAWESI BARAT,64.34,62.96,63.60,64.30,12.48,7.21,3.16,16.77,63.620000
30,MALUKU,65.40,67.05,67.60,68.19,13.91,0.87,0.77,1.09,67.613333
31,MALUKU UTARA,67.54,65.91,66.63,67.20,13.56,1.32,0.41,3.62,66.580000
32,PAPUA BARAT,65.32,61.73,62.21,62.99,12.47,2.84,1.94,5.55,62.310000
33,PAPUA,65.14,57.25,58.05,59.09,10.54,26.11,24.66,30.46,58.130000

In [37]:
#mengambil data Provinsi Jawa 
Jawa = data[10:16]
Jawa

,Provinsi,Angka Harapan Hidup,IPM 2015,IPM 2016,IPM 2017,Harapan Lama Sekolah,Presentase Buta Huruf Usia >15,Presentase Buta Huruf Usia 15-44,Presentase Buta Huruf Usia >44,Rata-Rata Lama Sekolah Umur >15 Tahun,Rata-Rata IPM
10,DKI JAKARTA,72.55,78.99,79.60,80.06,12.86,0.33,0.06,0.92,10.92,79.550000
11,JAWA BARAT,72.47,69.50,70.05,70.69,12.42,1.77,0.26,4.71,8.41,70.080000
12,JAWA TENGAH,74.08,69.49,69.98,70.52,12.57,6.61,0.36,15.38,7.70,69.996667
13,DI YOGYAKARTA,74.74,77.59,78.38,78.89,15.42,5.36,0.20,12.38,9.62,78.286667
14,JAWA TIMUR,70.80,68.95,69.74,70.27,13.09,8.18,1.01,18.27,7.78,69.653333
15,BANTEN,69.49,70.27,70.96,71.42,12.78,2.43,0.21,7.97,8.79,70.883333